name: base
channels:  
  - conda-forge  
dependencies:  
  - appmode  
  - earthengine-api
  - ipython
  - ipython_genutils
  - ipywidgets
  - pip
  - pip:    
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - httplib2
    - ipyleaflet
